import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { viVN } from "@clerk/localizations";
import ReactQueryProvider from "./ReactQueryProvider";
import localFont from "next/font/local";

const montserrat = localFont({
  src: [
    {
      path: "./Montserrat-VariableFont_wght.ttf",
      style: "normal",
    },
    {
      path: "./Montserrat-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
  ],
});
// import { Montserrat } from "next/font/google";

// const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={viVN}>
      <html lang="vi">
        <body className={`${montserrat.className} bg-white`}>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
