import "./globals.css";
import localFont from "next/font/local";

const montserrat = localFont({
  src: [
    {
      path: "./Montserrat-VariableFont_wght.ttf",
      style: "normal",
    },
    {
      path: "./Montserrat-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
  ],
});
// import { Montserrat } from "next/font/google";

// const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
